# Generated by Django 3.2.6 on 2021-08-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(help_text='icon name', max_length=32, null=True, verbose_name='icon name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(help_text='parent menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='parent menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(default='/', help_text='目录名或文件名', max_length=100, verbose_name='directory name/file name'),
        ),
    ]
