# Generated by Django 3.2.6 on 2021-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(help_text='database name', max_length=50, verbose_name='database name')),
                ('db_host', models.GenericIPAddressField(help_text='database port', protocol='IPv4', verbose_name='database host')),
                ('db_username', models.CharField(help_text='database username', max_length=50, verbose_name='database username')),
                ('db_password', models.CharField(help_text='database password', max_length=50, verbose_name='database password')),
                ('db_port', models.IntegerField(help_text='database port', verbose_name='database port')),
                ('db_default_schema', models.CharField(help_text='database default schema', max_length=20, verbose_name='database default schema')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('description', models.CharField(default=None, help_text='description', max_length=200, null=True, verbose_name='description')),
            ],
            options={
                'db_table': 't_database',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default=None, help_text='database type name', max_length=30, verbose_name='database type name')),
                ('type_icon', models.CharField(default=None, help_text='database type icon', max_length=30, verbose_name='database type icon')),
            ],
            options={
                'db_table': 't_database_type',
                'ordering': ['id'],
            },
        ),
    ]
