# Generated by Django 3.2.6 on 2021-08-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='main_account',
            field=models.CharField(default=None, help_text='main account for tencent', max_length=100, null=True, verbose_name='main account'),
        ),
        migrations.AddField(
            model_name='resource',
            name='ram_password',
            field=models.CharField(default=None, help_text='ram user password', max_length=100, verbose_name='ram_password'),
        ),
        migrations.AddField(
            model_name='resource',
            name='ram_username',
            field=models.CharField(default=None, help_text='ram user', max_length=100, verbose_name='ram_user'),
        ),
    ]
