# Generated by Django 3.2.6 on 2021-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GICategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default=None, help_text='type name', max_length=100, null=True, verbose_name='type_name')),
                ('comment', models.CharField(default=None, help_text='comment', max_length=100, null=True, verbose_name='comment')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
            ],
            options={
                'db_table': 't_gi_category',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='plant',
            name='comment',
            field=models.CharField(default=None, help_text='plant_name', max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_code',
            field=models.CharField(default=None, help_text='plant_name', max_length=100, null=True, verbose_name='plant_code'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(default=None, help_text='plant_name', max_length=100, null=True, verbose_name='plant_name'),
        ),
        migrations.AlterField(
            model_name='technologycode',
            name='comment',
            field=models.CharField(default=None, help_text='plant_name', max_length=100, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='technologycode',
            name='plant_tech_code',
            field=models.CharField(default=None, help_text='plant_name', max_length=100, null=True, verbose_name='plant_tech_code'),
        ),
        migrations.AlterField(
            model_name='technologycode',
            name='plant_tech_code_name',
            field=models.CharField(default=None, help_text='plant_name', max_length=100, null=True, verbose_name='plant_tech_code_name'),
        ),
    ]
