# Generated by Django 3.2.6 on 2021-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialPlanning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='Calibration',
            new_name='calibration',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='Currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='Dimension',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='Drawing',
            new_name='drawing',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='EngineerUser',
            new_name='engineer_user',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='EquipmentName',
            new_name='equipment_name',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='ImportanceLevel',
            new_name='importance_level',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='InstallationQuantity',
            new_name='installation_quantity',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='ManufacturerModel',
            new_name='manufacturer_model',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='ManufacturerName',
            new_name='manufacturer_name',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='ManufacturerPartNumber',
            new_name='manufacturer_part_number',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='MaterialNumber',
            new_name='material_number',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='PartSpecialTreatment',
            new_name='part_special_treatment',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='PlantTechCode',
            new_name='plant_tech_code',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='PurchaseType',
            new_name='purchase_type',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='Repairable',
            new_name='repairable',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='StorageLocation',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='Unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='UnitPrice',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='GICategory',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='HandoverStock',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='MaxStock',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='MinStock',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='PartDescriptionEN',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='PartDescriptionZh',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SupplierCode',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SupplierContactPerson',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SupplierContactPhone',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SupplierEmail',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SupplierModel',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SupplierName',
        ),
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SupplierPartNumber',
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='gi_category',
            field=models.CharField(default=None, help_text='gi_category', max_length=100, null=True, verbose_name='GI类别'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='handover_stock',
            field=models.CharField(default=None, help_text='Handover Stock', max_length=100, null=True, verbose_name='初始移交库存'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='max_stock',
            field=models.CharField(default=None, help_text='Max Stock', max_length=100, null=True, verbose_name='最大库存量'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='min_stock',
            field=models.CharField(default=None, help_text='Min Stock', max_length=100, null=True, verbose_name='安全库存'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='part_description_en',
            field=models.CharField(default=None, help_text='Part Description EN', max_length=100, null=True, verbose_name='零件描述(英文)'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='part_description_zh',
            field=models.CharField(default=None, help_text='Part Description Zh', max_length=100, null=True, verbose_name='零件描述(中文)'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='supplier_code',
            field=models.CharField(default=None, help_text='Supplier Code', max_length=100, null=True, verbose_name='供应商编码'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='supplier_contact_person',
            field=models.CharField(default=None, help_text='Supplier Contact Person', max_length=100, null=True, verbose_name='供应商联系人'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='supplier_contact_phone',
            field=models.CharField(default=None, help_text='Supplier Contact Phone', max_length=100, null=True, verbose_name='供应商联系电话'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='supplier_email',
            field=models.CharField(default=None, help_text='Supplier Email', max_length=100, null=True, verbose_name='供应商邮箱'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='supplier_model',
            field=models.CharField(default=None, help_text='Supplier Model', max_length=100, null=True, verbose_name='供应商的规格型号'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='supplier_name',
            field=models.CharField(default=None, help_text='Supplier Name', max_length=100, null=True, verbose_name='供应商名称'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='supplier_part_number',
            field=models.CharField(default=None, help_text='Supplier Part Number', max_length=100, null=True, verbose_name='供应商的订货号'),
        ),
    ]
