# Generated by Django 3.2.6 on 2021-10-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20211024_1816'),
        ('materialPlanning', '0002_auto_20211024_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialplanningmodel',
            name='SurplusStock',
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='surplus_stock',
            field=models.CharField(default=None, help_text='Surplus Stock', max_length=100, null=True, verbose_name='剩余库存'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='equipment_name',
            field=models.CharField(default=None, help_text='Equipment Name', max_length=100, null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='gi_category',
            field=models.ForeignKey(help_text='GI类别', on_delete=django.db.models.deletion.CASCADE, related_name='gi_category', to='material.gicategorymodel', verbose_name='gi_category'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='installation_quantity',
            field=models.CharField(default=None, help_text='Installation Quantity', max_length=100, null=True, verbose_name='安装数量'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='manufacturer_model',
            field=models.CharField(default=None, help_text='Manufacturer Model', max_length=100, null=True, verbose_name='制造商的规格型号'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='manufacturer_name',
            field=models.CharField(default=None, help_text='Manufacturer Name', max_length=100, null=True, verbose_name='制造商名称'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='manufacturer_part_number',
            field=models.CharField(default=None, help_text='Manufacturer Part Number', max_length=100, null=True, verbose_name='制造商的订货号'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='material_group_name',
            field=models.ForeignKey(help_text='Material Group', on_delete=django.db.models.deletion.CASCADE, related_name='material_group_name', to='material.materialgroup', verbose_name='material_group_name'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='part_special_treatment',
            field=models.CharField(default=None, help_text='PartSpecial Treatment', max_length=100, null=True, verbose_name='零件特殊处理'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='plant_tech_code',
            field=models.ForeignKey(help_text='Technology Code', on_delete=django.db.models.deletion.CASCADE, related_name='plant_tech_code_info', to='material.technologycode', verbose_name='plant_tech_code_info'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='unit_price',
            field=models.CharField(default=None, help_text='Unit Price', max_length=100, null=True, verbose_name='单价'),
        ),
    ]
