# Generated by Django 3.2.6 on 2021-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialPlanning', '0003_auto_20211024_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningStatusRuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default=None, help_text='status name', max_length=100, null=True, verbose_name='status name')),
                ('next_status_name', models.CharField(default=None, help_text='next status name', max_length=100, null=True, verbose_name='next status name')),
                ('comment', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='comment')),
            ],
            options={
                'db_table': 't_material_planning_status',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='materialplanningmodel',
            old_name='FCNo',
            new_name='fc_no',
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='create time', null=True, verbose_name='create time'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='planning_status',
            field=models.CharField(choices=[(1, 'Start'), (2, 'Waiting'), (3, 'MRHConfirming'), (4, 'Pending'), (5, 'MRHConfirmed'), (6, 'STRConfirming'), (7, 'STRConfirmed'), (8, 'STRBalanced'), (9, 'STRFinished'), (10, 'OTBCollection'), (11, 'PRProcessing'), (12, 'OrderCreating'), (13, 'OrderConfirming'), (14, 'OrderConfirmed'), (15, 'Producing'), (16, 'Delivery'), (17, 'GoodsReady'), (18, 'GoodsReceived'), (19, 'Invoice')], default='Start', help_text='Planning status', max_length=100, verbose_name='current status'),
        ),
        migrations.AddField(
            model_name='materialplanningmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True, help_text='update time', verbose_name='update time'),
        ),
        migrations.AlterField(
            model_name='materialplanningmodel',
            name='storage_location',
            field=models.CharField(default=None, help_text='Storage Location', max_length=100, null=True, verbose_name='存储库位'),
        ),
    ]
