# Generated by Django 3.2.6 on 2021-08-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='is_origin',
            field=models.BooleanField(default=True, help_text='is synced from cloud or not', verbose_name='is synced from cloud or not'),
        ),
        migrations.CreateModel(
            name='ServerALiCloudUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_username', models.CharField(help_text='server username', max_length=50, verbose_name='server username')),
                ('server_password', models.CharField(default=None, help_text='server_password', max_length=100, null=True, verbose_name='server password')),
                ('server_private_key', models.TextField(default=None, help_text='server private key', null=True, verbose_name='server private key')),
                ('has_sudo_perm', models.BooleanField(default=False, help_text='has sudo permission', verbose_name='has sudo permission')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('description', models.CharField(default=None, help_text='description', max_length=200, null=True, verbose_name='description')),
                ('belong_instance', models.ForeignKey(help_text='belong instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong_instance', to='servers.serveralicloudinstancemodel', verbose_name='belong instance')),
            ],
            options={
                'db_table': 't_server_user',
                'ordering': ['id'],
            },
        ),
    ]
