# Generated by Django 3.2.6 on 2021-08-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveralicloudinstancemodel',
            name='Cpu',
            field=models.CharField(default=None, help_text='Cpu', max_length=10, null=True, verbose_name='Cpu'),
        ),
        migrations.AlterField(
            model_name='serveralicloudinstancemodel',
            name='InstanceNetworkType',
            field=models.CharField(default=None, help_text='InstanceNetworkType', max_length=100, null=True, verbose_name='InstanceNetworkType'),
        ),
        migrations.AlterField(
            model_name='serveralicloudinstancemodel',
            name='Memory',
            field=models.CharField(default=None, help_text='Memory(MB)', max_length=10, null=True, verbose_name='Memory'),
        ),
    ]
