# Generated by Django 3.2.6 on 2021-08-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20210821_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveralicloudinstancemodel',
            name='InstanceName',
            field=models.CharField(default=None, help_text='InstanceName', max_length=100, null=True, unique=True, verbose_name='实例名称'),
        ),
    ]
