# Generated by Django 3.2.6 on 2021-08-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_alter_serveralicloudinstancemodel_instancename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveralicloudinstancemodel',
            name='OSNameEn',
            field=models.CharField(default=None, help_text='OSNameEn', max_length=100, null=True, verbose_name='实例操作系统的英文名称'),
        ),
    ]
