# Generated by Django 3.2.6 on 2021-08-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_serveralicloudinstancemodel_osnameen'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='LastUpdateTime',
            field=models.DateTimeField(auto_now=True, help_text='last update time', verbose_name='last update datetime'),
        ),
    ]
