# Generated by Django 3.2.6 on 2021-08-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20210821_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='ExpiredTime',
            field=models.DateTimeField(auto_now=True, help_text='start time', verbose_name='ExpiredTime'),
        ),
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='HostName',
            field=models.CharField(default=None, help_text='Cpu', max_length=100, null=True, verbose_name='HostName'),
        ),
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='IpAddress',
            field=models.CharField(default=None, help_text='IpAddress', max_length=39, null=True, verbose_name='IpAddress'),
        ),
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='OSType',
            field=models.CharField(default=None, help_text='OSType', max_length=40, null=True, verbose_name='OSType'),
        ),
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='RegionId',
            field=models.CharField(default=None, help_text='RegionId', max_length=40, null=True, verbose_name='RegionId'),
        ),
        migrations.AddField(
            model_name='serveralicloudinstancemodel',
            name='StartTime',
            field=models.DateTimeField(auto_now=True, help_text='start time', verbose_name='StartTime'),
        ),
    ]
