# Generated by Django 3.2.6 on 2021-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_username',
            field=models.CharField(help_text='GITHUB ACCOUNT', max_length=50, null=True, verbose_name='GITHUB ACCOUNT'),
        ),
    ]
