# Generated by Django 3.2.6 on 2021-08-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_github_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'permissions': (('can_view_user', 'cat view user'),), 'verbose_name': 'user'},
        ),
    ]
