# Generated by Django 3.2.6 on 2021-10-24 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowEntityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_flow_name', models.CharField(default=None, help_text='work flow name', max_length=100, null=True, verbose_name='work flow name')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('create_user', models.ForeignKey(help_text='负责人信息', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_entity_create_user', to=settings.AUTH_USER_MODEL, verbose_name='workflow_entity_create_user')),
            ],
            options={
                'db_table': 't_workflow_entity',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default=None, help_text='type name', max_length=100, null=True, verbose_name='type_name')),
                ('comment', models.CharField(default=None, help_text='comment', max_length=100, null=True, verbose_name='comment')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
            ],
            options={
                'db_table': 't_workflow_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_flow_name', models.CharField(default=None, help_text='work flow name', max_length=100, null=True, verbose_name='work flow name')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('update_at', models.DateTimeField(auto_now_add=True, help_text='update time', verbose_name='update time')),
                ('create_user', models.ForeignKey(help_text='负责人信息', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_create_user', to=settings.AUTH_USER_MODEL, verbose_name='workflow_create_user')),
                ('work_flow_type', models.ForeignKey(help_text='负责人信息', on_delete=django.db.models.deletion.CASCADE, related_name='work_flow_type_for_template', to='workflow.workflowtypemodel', verbose_name='work_flow_type_for_template')),
            ],
            options={
                'db_table': 't_workflow',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlowItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=None, help_text='item name', max_length=100, null=True, verbose_name='item_name')),
                ('item_status', models.CharField(default=None, help_text='item status', max_length=100, null=True, verbose_name='item_status')),
                ('is_begin_or_end', models.BooleanField(default=False, help_text='is begin or end status', verbose_name='is begin or end status')),
                ('item_last_status', models.CharField(default=None, help_text='item last status', max_length=100, null=True, verbose_name='item last status')),
                ('item_next_status', models.CharField(default=None, help_text='item next status', max_length=100, null=True, verbose_name='item next status')),
                ('audit_group', models.ForeignKey(help_text='审批role', on_delete=django.db.models.deletion.CASCADE, related_name='audit_group', to='auth.group', verbose_name='audit_group')),
                ('belong_work_flow', models.ForeignKey(help_text='belong work flow', on_delete=django.db.models.deletion.CASCADE, related_name='belong_work_flow', to='workflow.workflowmodel', verbose_name='belong_work_flow')),
            ],
            options={
                'db_table': 't_workflow_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlowItemEntityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default=None, help_text='item name', max_length=100, null=True, verbose_name='item_name')),
                ('item_status', models.CharField(default=None, help_text='item status', max_length=100, null=True, verbose_name='item_status')),
                ('is_begin_or_end', models.BooleanField(default=False, help_text='is begin or end status', verbose_name='is begin or end status')),
                ('item_last_status', models.CharField(default=None, help_text='item last status', max_length=100, null=True, verbose_name='item last status')),
                ('item_next_status', models.CharField(default=None, help_text='item next status', max_length=100, null=True, verbose_name='item next status')),
                ('belong_work_flow', models.ForeignKey(help_text='belong work flow', on_delete=django.db.models.deletion.CASCADE, related_name='belong_work_flow', to='workflow.workflowentitymodel', verbose_name='belong_work_flow')),
                ('belong_work_flow_template', models.ForeignKey(help_text='belong work flow', on_delete=django.db.models.deletion.CASCADE, related_name='belong_work_flow_template', to='workflow.workflowmodel', verbose_name='belong_work_flow_template')),
            ],
            options={
                'db_table': 't_workflow_item_entity',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='workflowentitymodel',
            name='work_flow_type',
            field=models.ForeignKey(help_text='负责人信息', on_delete=django.db.models.deletion.CASCADE, related_name='work_flow_type_for_entity', to='workflow.workflowtypemodel', verbose_name='work_flow_type_for_entity'),
        ),
    ]
