# Generated by Django 3.2.6 on 2021-08-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default=None, help_text='project type name', max_length=30, verbose_name='project type name')),
                ('type_icon', models.CharField(default=None, help_text='project type icon', max_length=30, verbose_name='project type icon')),
            ],
            options={
                'db_table': 't_project_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='project name', max_length=50, unique=True, verbose_name='project name')),
                ('github_repo_url', models.CharField(default=None, help_text='github repo url', max_length=100, verbose_name='github_repo_url')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('description', models.CharField(default=None, help_text='description', max_length=200, null=True, verbose_name='description')),
                ('belong_group', models.ForeignKey(help_text='belong group', on_delete=django.db.models.deletion.CASCADE, related_name='belong_group', to='auth.group', verbose_name='belong group')),
                ('create_user', models.ForeignKey(help_text='create user', on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='create user')),
                ('deployment_server_dev', models.ForeignKey(default=None, help_text='deployment server dev', on_delete=django.db.models.deletion.CASCADE, related_name='deployment_server_dev', to='servers.serveralicloudinstancemodel', verbose_name='deployment server dev')),
                ('deployment_server_prod', models.ForeignKey(default=None, help_text='deployment server prod', on_delete=django.db.models.deletion.CASCADE, related_name='deployment_server_prod', to='servers.serveralicloudinstancemodel', verbose_name='deployment server prod')),
                ('dev_users', models.ManyToManyField(blank=True, help_text='dev users', related_name='dev_users', to=settings.AUTH_USER_MODEL, verbose_name='dev users')),
                ('ops_users', models.ManyToManyField(blank=True, help_text='ops users', related_name='ops_users', to=settings.AUTH_USER_MODEL, verbose_name='ops users')),
                ('project_type', models.ForeignKey(help_text='project type', on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='project.projecttype', verbose_name='project type')),
            ],
            options={
                'db_table': 't_project',
                'ordering': ['id'],
            },
        ),
    ]
