# Generated by Django 3.2.6 on 2021-08-21 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0007_auto_20210821_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default=None, help_text='project type name', max_length=30, verbose_name='project type name')),
                ('type_icon', models.CharField(default=None, help_text='project type icon', max_length=30, verbose_name='project type icon')),
            ],
            options={
                'db_table': 't_project_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default=None, help_text='project type name', max_length=50, verbose_name='project type name')),
                ('github_repo_url', models.CharField(default=None, help_text='github repo url', max_length=1000, verbose_name='github_repo_url')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('belong_group', models.ForeignKey(help_text='belong group', on_delete=django.db.models.deletion.CASCADE, related_name='belong_group', to='auth.group', verbose_name='belong group')),
                ('create_user', models.ForeignKey(help_text='belong user', on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='belong user')),
                ('deployment_server', models.ManyToManyField(blank=True, help_text='deployment_server', related_name='deployment_server', to='servers.ServerAliCloudInstanceModel', verbose_name='deployment server')),
                ('project_type', models.ForeignKey(help_text='project type', on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='project.projecttype', verbose_name='project type')),
            ],
            options={
                'db_table': 't_project',
                'ordering': ['id'],
            },
        ),
    ]
