# Generated by Django 3.2.6 on 2021-08-21 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20210821_1419'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='create_user',
            field=models.ForeignKey(help_text='create user', on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='create user'),
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='deployment_server',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='deployment_server',
            field=models.ForeignKey(default=None, help_text='project type', on_delete=django.db.models.deletion.CASCADE, related_name='deployment_server', to='servers.serveralicloudinstancemodel', verbose_name='project type'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='github_repo_url',
            field=models.CharField(default=None, help_text='github repo url', max_length=1000, null=True, verbose_name='github_repo_url'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_name',
            field=models.CharField(default=None, help_text='project name', max_length=50, verbose_name='project name'),
        ),
    ]
