# Generated by Django 3.2.6 on 2021-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20210821_1419'),
        ('project', '0002_auto_20210821_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='deployment_server',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='deployment_server',
            field=models.ManyToManyField(blank=True, help_text='deployment server', related_name='deployment_server', to='servers.ServerAliCloudInstanceModel', verbose_name='deployment server'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='github_repo_url',
            field=models.CharField(default=None, help_text='github repo url', max_length=100, verbose_name='github_repo_url'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_name',
            field=models.CharField(help_text='project name', max_length=50, unique=True, verbose_name='project name'),
        ),
    ]
