# Generated by Django 3.2.6 on 2021-08-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20210821_1419'),
        ('project', '0003_auto_20210821_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='deployment_server',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='deployment_server_dev',
            field=models.ForeignKey(default=None, help_text='deployment server dev', on_delete=django.db.models.deletion.CASCADE, related_name='deployment_server_dev', to='servers.serveralicloudinstancemodel', verbose_name='deployment server dev'),
        ),
    ]
