# Generated by Django 3.2.6 on 2021-08-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20210821_1419'),
        ('project', '0004_auto_20210821_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='deployment_server_prod',
            field=models.ForeignKey(default=None, help_text='deployment server prod', on_delete=django.db.models.deletion.CASCADE, related_name='deployment_server_prod', to='servers.serveralicloudinstancemodel', verbose_name='deployment server prod'),
        ),
    ]
